/*
 * (c) VAP Communications Group, 2022
 */

package online.vapcom.swcomp.ui.theme

import androidx.compose.ui.graphics.Color

// заготовка цветовой палитры для Material Design 3
// сделано на https://material-foundation.github.io/material-theme-builder/ (любит Chrome)

val md_theme_light_primary = Color(0xFF00668a)
val md_theme_light_onPrimary = Color(0xFFffffff)
//val md_theme_light_primaryContainer = Color(0xFFc0e8ff)
//val md_theme_light_onPrimaryContainer = Color(0xFF001e2c)
val md_theme_light_secondary = Color(0xFF0057d0)
val md_theme_light_onSecondary = Color(0xFFffffff)
//val md_theme_light_secondaryContainer = Color(0xFFd8e2ff)
//val md_theme_light_onSecondaryContainer = Color(0xFF001947)
//val md_theme_light_tertiary = Color(0xFF00696c)
//val md_theme_light_onTertiary = Color(0xFFffffff)
//val md_theme_light_tertiaryContainer = Color(0xFF6ff6f9)
//val md_theme_light_onTertiaryContainer = Color(0xFF002021)
val md_theme_light_error = Color(0xFFba1b1b)
//val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
//val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfcfe)
val md_theme_light_onBackground = Color(0xFF191c1e)
val md_theme_light_surface = Color(0xFFfbfcfe)
val md_theme_light_onSurface = Color(0xFF191c1e)
val md_theme_light_surfaceVariant = Color(0xFFdce3e9)
//val md_theme_light_onSurfaceVariant = Color(0xFF41484d)
//val md_theme_light_outline = Color(0xFF71787d)
//val md_theme_light_inverseOnSurface = Color(0xFFf0f1f3)
//val md_theme_light_inverseSurface = Color(0xFF2e3133)

val md_theme_dark_primary = Color(0xFF71d1ff)
val md_theme_dark_onPrimary = Color(0xFF003549)
//val md_theme_dark_primaryContainer = Color(0xFF004c68)
//val md_theme_dark_onPrimaryContainer = Color(0xFFc0e8ff)
val md_theme_dark_secondary = Color(0xFFafc6ff)
val md_theme_dark_onSecondary = Color(0xFF002c72)
//val md_theme_dark_secondaryContainer = Color(0xFF00409f)
//val md_theme_dark_onSecondaryContainer = Color(0xFFd8e2ff)
//val md_theme_dark_tertiary = Color(0xFF4cd9dc)
//val md_theme_dark_onTertiary = Color(0xFF003739)
//val md_theme_dark_tertiaryContainer = Color(0xFF004f51)
//val md_theme_dark_onTertiaryContainer = Color(0xFF6ff6f9)
val md_theme_dark_error = Color(0xFFffb4a9)
//val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
//val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1e)
val md_theme_dark_onBackground = Color(0xFFe1e2e5)
val md_theme_dark_surface = Color(0xFF191c1e)
val md_theme_dark_onSurface = Color(0xFFe1e2e5)
val md_theme_dark_surfaceVariant = Color(0xFF41484d)
//val md_theme_dark_onSurfaceVariant = Color(0xFFc0c7cd)
//val md_theme_dark_outline = Color(0xFF8b9297)
//val md_theme_dark_inverseOnSurface = Color(0xFF191c1e)
//val md_theme_dark_inverseSurface = Color(0xFFe1e2e5)

//val seed = Color(0xFF00c1ff)
val error = Color(0xFFba1b1b)